# This file was generated by GoReleaser. DO NOT EDIT.
class Vestibule < Formula
  desc "Gather secrets from various backends and inject them into the process environment"
  homepage "https://github.com/lumoslabs/vestibule"
  url "https://github.com/lumoslabs/vestibule/releases/download/v1.2.2/vestibule_1.2.2_Darwin_x86_64.tar.gz"
  version "1.2.2"
  sha256 "27f5e2626721f44d386abe5141d8685d553013e71fc029a53a34d52f46490911"

  def install
    bin.install "vest"
    bin.install "bule"
  end

  test do
    system "#{bin}/vest --version"
    system "#{bin}/bule --version"
  end
end
